### ISSUE TITLE
Startup Video Frozen

### ISSUE THREAD

**Issue by ghost** [MalcolmMielle/ros_open_tld#2]
Hi,

I've been trying your code out on Indigo under 14.04.
It seems to compile without issue.
I use the standard usb_cam package from Indigo for video.
When running the ros_tld_gui.launch (after passing the camera topic), I get a frozen image from the webcam, from the moment it starts up.
I would be happy to attempt to debug this myself, but if you could point me in the right direction, I would appreciate it.

**Comment by MalcolmMielle** [comment]
Hej,

I stopped developping this project couple of years ago so I am not going to be of much help I think, sorry :/. But nevertheless, if you don't mind a PCL dependency, could you try [this package](https://github.com/MalcolmMielle/ros_open_tld_3d) instead ?

You could also try the OpenTLD [code](http://www.gnebehay.com/tld/) by itself and see if the problem is comming from this package and ros or from the tracker's code itself.

**Comment by ghost** [comment]
Thanks very much appreciate it.

**Comment by MalcolmMielle** [comment]
Sorry I can't do more :/
